### ISSUE TITLE
GitHub Issue: Improving CSS Code for ToDoList Webpage

### ISSUE THREAD

**Issue by the-faizmohammad** [the-faizmohammad/Project-To-Do-List#5]
GitHub Issue: Improving CSS Code for ToDoList Webpage

Description:
The current CSS code for the ToDoList webpage needs some improvements to follow best practices and enhance its responsiveness. Below are the areas where we can make improvements:

Areas for Improvement:

Use Relative Units: Replace fixed pixel values with relative units like em, rem, or percentages for padding, width, height, and font sizes to ensure a responsive design on different screen sizes.

Over-Specifying Selectors: Avoid overly specific selectors like ul#do-list. Using just the ID or class name directly would be sufficient unless there are specific requirements that demand such specificity.

Avoid Inline Styles: Remove any inline styles and move them to the CSS file to improve code organization and maintainability.

CSS Organization: Group related styles together and add comments to indicate the purpose of each section for better readability and maintenance.

Responsive Design: Ensure that the design adapts well to various screen sizes by using media queries or relative units.

Consistent Naming Convention: Adopt a consistent naming convention for class and ID names throughout the CSS.
```css
.main-heading {
  display: flex;
  width: 100%;
  justify-content: space-between;
  align-items: center;
  padding: 12px;
  border-bottom: 1px solid #c6c6c7;
}

.reload-image {
  width: 24px;
  height: 24px;
}

.adding-list {
  width: 100%;
  padding: 12px;
  border-bottom: 1px solid #c6c6c7;
  display: flex;
  align-items: center;
}

.list-adding:hover {
  background: #e4e4ff;
  border: 1px solid #bfcca5;
}

#add-new-list {
  width: 100%;
  padding: 4px;
  font-size: 18px;
  border: none;
  outline: none;
  background: none;
}
``` 
https://github.com/the-faizmohammad/Project-To-Do-List/blob/484db32f7d1a08d84424b23f0e178deff7a0b248/src/style.css#L53C1-L54C1
Suggested Changes:
Feel free to propose your improvements and solutions to the issues mentioned above. Once the changes are reviewed, we can proceed with updating the CSS to enhance the ToDoList webpage's design and functionality.

Looking forward to your valuable contributions!
